# Generated by Django 5.1.2 on 2024-10-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(blank=True, null=True)),
                ('prod_app', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.CharField(choices=[('TE', 'Tea'), ('CE', 'Coffee'), ('SN', 'Snaks'), ('GF', 'Gifts')], max_length=10)),
                ('product_images', models.ImageField(blank=True, null=True, upload_to='product')),
            ],
        ),
    ]
