# Generated by Django 5.1.2 on 2024-10-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_images',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TE', 'Tea'), ('CE', 'Coffee'), ('SN', 'Snacks'), ('GF', 'Gifts')], max_length=10, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='composition',
            field=models.TextField(blank=True, null=True, verbose_name='Composition'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prod_app',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Product Application'),
        ),
    ]
