# Generated by Django 5.1.1 on 2024-12-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_cart_unique_together_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TE', 'Tea'), ('CE', 'Coffee'), ('SN', 'Snacks'), ('GF', 'Gifts')], max_length=20, verbose_name='Product Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Product Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(verbose_name='Discounted Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.FloatField(verbose_name='Selling Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Product Title'),
        ),
    ]
